### ISSUE TITLE
Vídeo de como preencher a planilha de trabalho

### ISSUE THREAD

**Issue by Andreqlp** [Mutirao/SistemaDeEditaisSecult#14]

**Comment by Andreqlp** [comment]
Versão teste: https://www.youtube.com/watch?v=Tro5bJ7sUNc

**Comment by Andreqlp** [comment]
novo vídeo de como preencher o plano de trabalho: https://youtu.be/7ZlJjSjcC9g

Tb tomei a liberdade de adicionar, na seção de ajuda, do site dos editais uma nova página com documentos de referência. São os documentos que estavam presentes na página da Secult para inscrição, execução e prestação de contas, e adicionei as tabelas de referência de preços e as unidades de medida que tínhamos comentado no último tira dúvidas sobre o edital LGBT
http://editais.cultura.ce.gov.br/documentos-de-referencia/

Aguardando aprovação (foi enviado para o Matheus)

**Comment by geciola** [comment]
Resposta do Matheus: "Na minha opinião está ótimo, só me incomodei, no minuto 5:13, a unidade de medida "mês", que não está na tabela enviada anteriormente."

E ainda falta eu revisar esse vídeo, Jedas.

**Comment by Andreqlp** [comment]
Ok, ficarei aguardando a tua revisão para fazer a versão final.

**Comment by Andreqlp** [comment]
Versão final do vídeo: https://youtu.be/4Ufd8p33z-o
Já foi incluído na seção de ajuda do site (http://editais.cultura.ce.gov.br/2016/12/13/video-preenchimento-do-plano-de-trabalho/ ) e na seção de guia de perguntas e respostas.
