### ISSUE TITLE
Criar fluxo de divulgação de editais e oficinas

### ISSUE THREAD

**Issue by Andreqlp** [Mutirao/SistemaDeEditaisSecult#19]

**Comment by Andreqlp** [comment]
Denis:
sobre o criar e divulgar os editais acho que podemos pensar em montar um calendario integrado:
. comunicação institucional (secult)
. comunicação Mutirão/Mapa
. diretoria (repasse de datas dos lançamentos)

ai podemos pensar nos materiais pra gerir essa comunicação:
. memes
. video passo a passo como se inscrever
. conheça o edital xxx
. crie seu perfil no Mapa
. oficinas online (agendadas)
pensei nessas propostas, que vcs acham?

Jedi:
Não entendi muito bem o que seria essa diretoria.

Gostei da opção de criar memes para dar mais leveza a comunicação e também pensar nos públicos específicos.

Uma outra coisa que podemos fazer é criar mesmo esse plano de divulgação específico para o segmento do edital. A secult deve ter uma listas de e-mail, como também podemos mapear fóruns, grupos no face.... e já pensar num fluxo de relacionamento que se inicia no edital, mas que pode continuar no mapas e em outras ferramentas ou oportunidades que a Secult disponibiliza.

**Comment by alinacif** [comment]
sobre a **diretoria** foi apenas um forma de citar as coordenações que que acompanham e repassam as informações dos editais.

. sobre o fluxo dessa semana temos essas atividades sendo encaminhadas:

. Edital Cultura Infância - aberto até o dia 03/01/2017
- [x] Marcar oficinas presenciais e online:
. Presencial: 08/12, às 14h no auditório da Secult 
. Online: 14/12, às 19h30 via Youtube

Comunicação para as oficinas:
- [x] solicitar arte da oficina presencial e online (uma arte p/ cada)
- [x] solicitar postagem nas redes (site e página da Secult, site e pagina do Mutirão e Mapa Cultural)
- [x] criar evento da transmissão da oficina presencial e online no Youtube da Secult (Jedi, vai fazer)
- [x] marcar com coordenadores: Juridico (Dalune), Financeiro (Rafael) e Coordenador do Edital (Valeria Cordeiro)
- [x] solicitar pc, câmera, projetor (pedir a Carla, secretária)
- [x] solicitar auditório para o dia 08 (ver com a Carla)
- [x] pedir listas do inscritos no edital ao Nalomy (enviar email comunicando as oficinas)
- [x] enviar e-mail padrão a todos os participantes do edital comunicando das duas oficinas


ENVIOS DOS EMAIL:
- [x] 06/12 - disparo do primeiro email oficina presencial
- [x] 12/12 - disparo do segundo email oficina online

**Comment by Andreqlp** [comment]
@denisnacif transformei o check list para ficar editável o código para criar essas caixinhas é - [ ]

Marca quais da atividade vc já conseguiu fazer.

**Comment by alinacif** [comment]
foi aqui :)

**Comment by Andreqlp** [comment]
Denis, rolou direito a experiência do fluxo do Cultura e Infância ?  Você pode criar um documento padronizando esse check list para os futuros editais? 
Feito isso, acho que finalizamos essa issue :)

**Comment by alinacif** [comment]
rolou sim. como eu encerro aqui?

**Comment by alinacif** [comment]
link do Fluxo do edital >> https://docs.google.com/document/d/13DUfEqOdIF5aTA9bw-nFsMVOgYvbObyQKPddekwNo8M/edit
