### ISSUE TITLE
Revisar e divulgar calendário dos editais de 2016

### ISSUE THREAD

**Issue by Andreqlp** [Mutirao/SistemaDeEditaisSecult#22]

**Comment by alinacif** [comment]
sobre o criar e divulgar os editais acho que podemos pensar em montar um calendario integrado:
. comunicação institucional (secult)
. comunicação Mutirão/Mapa 
. diretoria (repasse de datas dos lançamentos)

>> ai podemos pensar nos materiais pra gerir essa comunicação:
. memes
. video passo a passo como se inscrever
. conheça o edital xxx
. crie seu perfil no Mapa
. oficinas online (agendadas)

pensei nessas propostas, que vcs acham?

**Comment by Andreqlp** [comment]
Não entendi muito bem o que seria essa diretoria.

Gostei da opção de criar memes para dar mais leveza a comunicação e também pensar nos públicos específicos. 

Uma outra coisa que podemos fazer é criar mesmo esse plano de divulgação específico para o segmento do edital. A secult deve ter uma listas de e-mail, como também podemos mapear fóruns, grupos no face.... e já pensar num fluxo de relacionamento que se inicia no edital, mas que pode continuar no mapas e em outras ferramentas ou oportunidades que a Secult disponibiliza.

**Comment by Andreqlp** [comment]
@denisnacif, tem uma issue chamada "Criar fluxo de divulgação de editais e oficinas", acredito que ela seja o lugar mais adequado para seguir com essa conversa. Copiei nossos textos para lá.

**Comment by alinacif** [comment]
massa Jedi, vou por la. Aproveito e insiro o que batemos ontem para as oficinas.

**Comment by Andreqlp** [comment]
@denisnacif , vc pode ver com a gecíola esse calendário? Tb é bom incluir os editais que estão em andamento.

**Comment by alinacif** [comment]
massa Jedi, posso ver isso hoje sim.
Sobre o calendario temos ate agora as duas oficinas, um lançamento semana que vem do Edital Patrimônio Cultural (tamo ainda tentando saber o que será pois Geciola ñ recebeu material ainda). é isso?

no restante é bater com o que ainda vai ser lançado para planejarmos.

**Comment by Andreqlp** [comment]
Mecenas, inscrições 21/12/16 a 20/01/17.
Cina e Vídeo, previsão de lançamento para o dia 28.
Incentivo as artes (9 linguagens), previsão de lançamento para o dia 28.

Referências na pasta do Sistema dos Editais: https://drive.google.com/drive/u/0/folders/0B4Q7Y_cuhmVKWmRmZGdMemlMNFU
Resumo dos editais lançados
Balanço dos editais 2016
Apresentação Editais Secult
Cronograma 2016/2017
