### ISSUE TITLE
Alimentacao da agenda pelos equipamentos da secult

### ISSUE THREAD

**Issue by alinacif** [Mutirao/SistemaDeEditaisSecult#30]
F5 - EQUIPAMENTOS SECULT
- [x] pegar lista de equipamentos/instituições que não utilizam o Mapa
- [x] marcar visita aos equipamentos
. criar perfil da equipe
. atualizar informações
. tirar dúvidas

- [x] Casa Juvenal Galeno | 85 3252.3561 >> Antonio Galeno
. perfil agente
> Rua General Sampaio, 1128 - centro
. marcado amanhã às 10h.

- [x] Sobrado Dr José Lourenço | 85 3101.8826 / 8827 >> Natalia
. perfil espaço
. perfil agente
> Rua Major Facundo, 154
. agendado, 07/12 - às 10h

- [x] Centro Dragão do Mar | Luar ou Luciana
. precisa atualizar apenas nos “colaboradores” as demais equipes que trabalham pelo IDM
- visita agendada >> 09/12m às 10h - Sala de Imprensa do Dragão

- [x]  Escola das Artes e Ofícios Thomaz Pompeu Sobrino 
> Avenida Francisco Sá, 1801 - Jacarecanga
- visita agendada >> 09/12m às 10h - Sala de Imprensa do Dragão

- [ ] Theatro José de Alencar | Kennedy Saldanha ou Ivy
perfil espaço - aqui a secult ta como agente
perfil agente 
- agendado, dia 15/12, às 10h

- [x] Escola Porto Iracema das Artes  | Analice e Bia
- agendado, dia 13/12, às 14h

- [ ] Cineteatro São Luiz |  Isabel ou Milton
. precisa atualizar apenas nos “colaboradores” as demais equipes que trabalham pelo Cineteatro
- agendado após o dia 20 de dezembro

- [ ]  Centro Cultural Bom Jardim | Amanda
> Rua 3 corações, 400 - Bom Jardim
- agendado, dia 22/12, às 14h

- [x]  Museu do Ceará | Marcela ou Carla
. perfil equipamento | perfil coletivo
. falei com a Marcela, ela ficou de retorna amanha e dar uma data para a visita.
- agendado, dia 13/12, às 10h

- [ ]  Museu da Imagem e do Som | Dilmar
> Avenida Barão de Studart, 410
- agendado, dia 09/12, às 15h

- [ ] Biblioteca Espaço Estação |  Rita de Cassia
Biblioteca Público do Ceará
> Rua 24 de maio, 60 - Centro
. falei com a Rita, pegou meu numero e ficou de retornar para marcar a visita

- [ ] Museu Sacro São José de Ribamar |Aureniza
> Praça Cônego Araripe, 22 - Aquiraz
- só chama, sigo tentando.

- [ ] Arquivo Público | Marcio
. perfil espaço
. perfil 
. retornar amanhã (07)
> Rua Senador Alencar, 348

- [ ] Teatro Carlos Câmara | Piancó
> Rua Senador Pompeu, 454 - Centro
. so chama

- [ ] Mausoléu Castelo Branco
> Av. Barão de Studart, 500 - Meireles
. Mausoléu Castelo Branco - http://mapa.cultura.ce.gov.br/espaco/498/
. Conjunto Palácio da Abolição e Mausoléu Castelo Branco http://mapa.cultura.ce.gov.br/espaco/227/ 

::PRECISO BATER
 ESSES::
Biblioteca Pública Dolor Barreira | (85) 3105-1299
> Av. da Universidade 2572, Benfica
Biblioteca Pública Menezes Pimentel
> Av. Presidente Castelo Branco, 255, 255, Próximo ao Centro Dragão do Mar,

**Comment by Andreqlp** [comment]
lembrar de relatar aqui como foi a experiência nesses equipamentos.
