### ISSUE TITLE
Vídeo com o passo a passo de como fazer o cadastro na plataforma Mapas Culturais e a inscrição nos editais

### ISSUE THREAD

**Issue by Andreqlp** [Mutirao/SistemaDeEditaisSecult#7]

**Comment by Andreqlp** [comment]
aguardando aprovação https://www.youtube.com/watch?v=WiPfHvgZuSU

**Comment by geciola** [comment]
Jedas, enfim consegui assistir o vídeo! Ficou ótimo! Seguem algumas considerações:

1:12 - Corrigir "um certo tira-dúvidas". O correto seria: "Também nessa descrição você vai ter as informações sobre como tirar dúvidas sobre cada edital em específico";
4:37 - Cortar "alguns editais entram nesse tipo de inscrição". Nenhum edital da Secult aceita coletivo sem CNPJ;
5:27 - Corrigir "na sequência, eu vou repetir meu nome". O correto seria "Na sequência, eu preciso informar meu nome completo, pois isso é obrigatório para participação nos editais da Secult".
6:33 - É importante escrever o endereço completo, pra pessoa entender o que tem que colocar em cada campo, pois isso é de extrema importância, para a Secult, que seja preenchido completamente. É importante também dizer que isso é obrigatório para inscrição nos editais.
10:09 - Você diz "e aí você vai ter o perfil do teu agente completo", mas não tá completo. Você passou direto sem falar dos campos tags, links para redes sociais, capa, avatar, site, gênero, orientação sexual, raça/cor, descrição completa. Acho importante mostrar o cadastramento completo de um perfil. Pra Secult isso é muito importante. Precisamos estimular a pessoa a preencher tudo. Estamos tendo dificuldades nos editais justamente porque a galera não preenche tudo.
10:25 - "No caso se você concorrer como proponente Pessoa Física, só isso basta". Isso está incorreto. Como você disse no início do vídeo, cada edital tem obrigatoriedades de informações diferentes. Se bem que agora acho que você quis dizer "no caso se você quiser concorrer como proponente Pessoa Física, basta o cadastro de agente individual".
10:38 - É importante dizer, de forma bem enfática, que não é necessário criar um novo cadastro com login e senha para o perfil coletivo (Pessoa Jurídica). Que com o mesmo login e senha da Pessoa Física você pode criar quantos agentes quiser. E é bom dar o exemplo: posso ter dois agentes individuais (um com meus dados de produtora e outro com meus dados de artista, p.ex.).
11:13 - Da mesma forma em relação ao agente individual, você passou direto por alguns campos na orientação de preenchimento do cadastro de agente coletivo.
15:30 - Você não falou a palavra "rascunho". É importante dizer as nomenclaturas das coisas.Tanto no áudio quanto no vídeo é importante colocar. "Você pode deixar sua inscrição em rascunho".
15:41 - Você diz que as inscrições ficam salvas no painel, mas o texto fala "perfil". Acho importante corrigir no texto.
16:06 - Corrigir "antes do último dia de inscrição". O correto é "você precisa enviar a inscrição até a data e hora indicada em cada edital. É importante não deixar para enviar a inscrição na última hora, pois o sistema pode congestionar e você não conseguir enviar a tempo".
17:51 - De novo você passou direto por campos. O site tava ali e você não mencionou. Acho importante explicar cada coisa, ser bem chato mesmo.
17:53 - Corrigir "No canto direito eu posso ter alguns anexos". Sugiro "No canto direito sempre serão disponibilizados o edital e seus anexos, além de corrigendas, aditivos ou outros documentos relacionados ao edital, e também o link para o tutorial da inscrição em texto".
18:01 - "Eu tenho um link de como fazer um tutorial". Oi???
18:44 - Corrigir "é o local onde eu vou acompanhar esse processo pelo Mapas". Sugiro "Este é um código único que vai permitir que eu possa acompanhar minha inscrição na plataforma".
18:46 - Corrigir para "se você for tirar dúvidas através do email e do telefone disponibilizados para cada edital, é necessário estar com esse código em mãos para informar e ser atendido na sua dúvida".
21:28 - Você não diz o título do campo (Período de Execução do Projeto - Início).
22:09 - É importante aqui dizer que o Plano de Trabalho é uma planilha de quatro abas que precisam ser completamente preenchidas (clicar nelas), e que existe um outro vídeo com orientações sobre como preencher esta planilha, que se encontra na seção Ajuda do site dos Editais.
24:29 - Aqui é importante reforçar que ele pode ver as inscrições enviadas lá no mesmo canto no painel, onde ele viu as que estavam em rascunho.
25:02 - Não tem uma aba com as perguntas mais frequentes. Tem uma seção Ajuda, que comporta os tutoriais em texto e vídeo, o FAQ e outras coisas. Será que não é melhor explicar direito?

**Comment by Andreqlp** [comment]
transferi as tuas observações para esse docs. Acho que é mais fácil fazer apontamentos por lá:
https://docs.google.com/document/d/1nBO4WwrPprZEmKlhoabDBTEingcLGG_Kzd5bjBxy8BQ/edit

**Comment by Andreqlp** [comment]
Versão finalizada do vídeo: https://youtu.be/F8Yy6LfDShs.
O mesmo já foi adicionado ao manual do passo a passo em texto.
